package com.troytan.sixpack.domain;

import java.util.Date;

public class Debate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_debate.DEBATE_ID
     *
     * @mbg.generated
     */
    private Integer debateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_debate.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_debate.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_debate.GROUP_ID
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_debate.STATUS
     *
     * @mbg.generated
     */
    private Short status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_debate.REVERSE
     *
     * @mbg.generated
     */
    private String reverse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_debate.OBVERSE
     *
     * @mbg.generated
     */
    private String obverse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_debate.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_debate.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_debate.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_debate.UPDATE_ON
     *
     * @mbg.generated
     */
    private Date updateOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_debate.DEBATE_ID
     *
     * @return the value of tt_debate.DEBATE_ID
     *
     * @mbg.generated
     */
    public Integer getDebateId() {
        return debateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_debate.DEBATE_ID
     *
     * @param debateId the value for tt_debate.DEBATE_ID
     *
     * @mbg.generated
     */
    public void setDebateId(Integer debateId) {
        this.debateId = debateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_debate.TITLE
     *
     * @return the value of tt_debate.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_debate.TITLE
     *
     * @param title the value for tt_debate.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_debate.CONTENT
     *
     * @return the value of tt_debate.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_debate.CONTENT
     *
     * @param content the value for tt_debate.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_debate.GROUP_ID
     *
     * @return the value of tt_debate.GROUP_ID
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_debate.GROUP_ID
     *
     * @param groupId the value for tt_debate.GROUP_ID
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_debate.STATUS
     *
     * @return the value of tt_debate.STATUS
     *
     * @mbg.generated
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_debate.STATUS
     *
     * @param status the value for tt_debate.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_debate.REVERSE
     *
     * @return the value of tt_debate.REVERSE
     *
     * @mbg.generated
     */
    public String getReverse() {
        return reverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_debate.REVERSE
     *
     * @param reverse the value for tt_debate.REVERSE
     *
     * @mbg.generated
     */
    public void setReverse(String reverse) {
        this.reverse = reverse == null ? null : reverse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_debate.OBVERSE
     *
     * @return the value of tt_debate.OBVERSE
     *
     * @mbg.generated
     */
    public String getObverse() {
        return obverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_debate.OBVERSE
     *
     * @param obverse the value for tt_debate.OBVERSE
     *
     * @mbg.generated
     */
    public void setObverse(String obverse) {
        this.obverse = obverse == null ? null : obverse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_debate.CREATE_BY
     *
     * @return the value of tt_debate.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_debate.CREATE_BY
     *
     * @param createBy the value for tt_debate.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_debate.CREATE_ON
     *
     * @return the value of tt_debate.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_debate.CREATE_ON
     *
     * @param createOn the value for tt_debate.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_debate.UPDATE_BY
     *
     * @return the value of tt_debate.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_debate.UPDATE_BY
     *
     * @param updateBy the value for tt_debate.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_debate.UPDATE_ON
     *
     * @return the value of tt_debate.UPDATE_ON
     *
     * @mbg.generated
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_debate.UPDATE_ON
     *
     * @param updateOn the value for tt_debate.UPDATE_ON
     *
     * @mbg.generated
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }
}