package com.troytan.sixpack.domain;

import java.util.Date;

public class GvoteReceive {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote_receive.RECEIVE_ID
     *
     * @mbg.generated
     */
    private Integer receiveId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote_receive.USER_ID
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote_receive.GVOTE_ID
     *
     * @mbg.generated
     */
    private Integer gvoteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote_receive.DELETED
     *
     * @mbg.generated
     */
    private Boolean deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote_receive.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote_receive.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote_receive.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote_receive.UPDATE_ON
     *
     * @mbg.generated
     */
    private Date updateOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote_receive.RECEIVE_ID
     *
     * @return the value of tt_gvote_receive.RECEIVE_ID
     *
     * @mbg.generated
     */
    public Integer getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote_receive.RECEIVE_ID
     *
     * @param receiveId the value for tt_gvote_receive.RECEIVE_ID
     *
     * @mbg.generated
     */
    public void setReceiveId(Integer receiveId) {
        this.receiveId = receiveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote_receive.USER_ID
     *
     * @return the value of tt_gvote_receive.USER_ID
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote_receive.USER_ID
     *
     * @param userId the value for tt_gvote_receive.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote_receive.GVOTE_ID
     *
     * @return the value of tt_gvote_receive.GVOTE_ID
     *
     * @mbg.generated
     */
    public Integer getGvoteId() {
        return gvoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote_receive.GVOTE_ID
     *
     * @param gvoteId the value for tt_gvote_receive.GVOTE_ID
     *
     * @mbg.generated
     */
    public void setGvoteId(Integer gvoteId) {
        this.gvoteId = gvoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote_receive.DELETED
     *
     * @return the value of tt_gvote_receive.DELETED
     *
     * @mbg.generated
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote_receive.DELETED
     *
     * @param deleted the value for tt_gvote_receive.DELETED
     *
     * @mbg.generated
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote_receive.CREATE_BY
     *
     * @return the value of tt_gvote_receive.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote_receive.CREATE_BY
     *
     * @param createBy the value for tt_gvote_receive.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote_receive.CREATE_ON
     *
     * @return the value of tt_gvote_receive.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote_receive.CREATE_ON
     *
     * @param createOn the value for tt_gvote_receive.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote_receive.UPDATE_BY
     *
     * @return the value of tt_gvote_receive.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote_receive.UPDATE_BY
     *
     * @param updateBy the value for tt_gvote_receive.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote_receive.UPDATE_ON
     *
     * @return the value of tt_gvote_receive.UPDATE_ON
     *
     * @mbg.generated
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote_receive.UPDATE_ON
     *
     * @param updateOn the value for tt_gvote_receive.UPDATE_ON
     *
     * @mbg.generated
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }
}