package com.troytan.sixpack.domain;

import java.util.Date;

public class Gvote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.GVOTE_ID
     *
     * @mbg.generated
     */
    private Integer gvoteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.MULTI
     *
     * @mbg.generated
     */
    private Boolean multi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.ANONYMOUS
     *
     * @mbg.generated
     */
    private Boolean anonymous;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.END_TIME
     *
     * @mbg.generated
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.MIN_COUNT
     *
     * @mbg.generated
     */
    private Short minCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.MAX_COUNT
     *
     * @mbg.generated
     */
    private Short maxCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.FINISHED
     *
     * @mbg.generated
     */
    private Boolean finished;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.OWNER
     *
     * @mbg.generated
     */
    private Integer owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.GROUP_ID
     *
     * @mbg.generated
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_gvote.UPDATE_ON
     *
     * @mbg.generated
     */
    private Date updateOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.GVOTE_ID
     *
     * @return the value of tt_gvote.GVOTE_ID
     *
     * @mbg.generated
     */
    public Integer getGvoteId() {
        return gvoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.GVOTE_ID
     *
     * @param gvoteId the value for tt_gvote.GVOTE_ID
     *
     * @mbg.generated
     */
    public void setGvoteId(Integer gvoteId) {
        this.gvoteId = gvoteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.TITLE
     *
     * @return the value of tt_gvote.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.TITLE
     *
     * @param title the value for tt_gvote.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.MULTI
     *
     * @return the value of tt_gvote.MULTI
     *
     * @mbg.generated
     */
    public Boolean getMulti() {
        return multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.MULTI
     *
     * @param multi the value for tt_gvote.MULTI
     *
     * @mbg.generated
     */
    public void setMulti(Boolean multi) {
        this.multi = multi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.ANONYMOUS
     *
     * @return the value of tt_gvote.ANONYMOUS
     *
     * @mbg.generated
     */
    public Boolean getAnonymous() {
        return anonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.ANONYMOUS
     *
     * @param anonymous the value for tt_gvote.ANONYMOUS
     *
     * @mbg.generated
     */
    public void setAnonymous(Boolean anonymous) {
        this.anonymous = anonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.END_TIME
     *
     * @return the value of tt_gvote.END_TIME
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.END_TIME
     *
     * @param endTime the value for tt_gvote.END_TIME
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.MIN_COUNT
     *
     * @return the value of tt_gvote.MIN_COUNT
     *
     * @mbg.generated
     */
    public Short getMinCount() {
        return minCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.MIN_COUNT
     *
     * @param minCount the value for tt_gvote.MIN_COUNT
     *
     * @mbg.generated
     */
    public void setMinCount(Short minCount) {
        this.minCount = minCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.MAX_COUNT
     *
     * @return the value of tt_gvote.MAX_COUNT
     *
     * @mbg.generated
     */
    public Short getMaxCount() {
        return maxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.MAX_COUNT
     *
     * @param maxCount the value for tt_gvote.MAX_COUNT
     *
     * @mbg.generated
     */
    public void setMaxCount(Short maxCount) {
        this.maxCount = maxCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.FINISHED
     *
     * @return the value of tt_gvote.FINISHED
     *
     * @mbg.generated
     */
    public Boolean getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.FINISHED
     *
     * @param finished the value for tt_gvote.FINISHED
     *
     * @mbg.generated
     */
    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.OWNER
     *
     * @return the value of tt_gvote.OWNER
     *
     * @mbg.generated
     */
    public Integer getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.OWNER
     *
     * @param owner the value for tt_gvote.OWNER
     *
     * @mbg.generated
     */
    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.GROUP_ID
     *
     * @return the value of tt_gvote.GROUP_ID
     *
     * @mbg.generated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.GROUP_ID
     *
     * @param groupId the value for tt_gvote.GROUP_ID
     *
     * @mbg.generated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.CREATE_BY
     *
     * @return the value of tt_gvote.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.CREATE_BY
     *
     * @param createBy the value for tt_gvote.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.CREATE_ON
     *
     * @return the value of tt_gvote.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.CREATE_ON
     *
     * @param createOn the value for tt_gvote.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.UPDATE_BY
     *
     * @return the value of tt_gvote.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.UPDATE_BY
     *
     * @param updateBy the value for tt_gvote.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_gvote.UPDATE_ON
     *
     * @return the value of tt_gvote.UPDATE_ON
     *
     * @mbg.generated
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_gvote.UPDATE_ON
     *
     * @param updateOn the value for tt_gvote.UPDATE_ON
     *
     * @mbg.generated
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }
}