package com.troytan.sixpack.domain;

import java.util.Date;

public class Plan {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan.PLAN_ID
     *
     * @mbg.generated
     */
    private Integer planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan.LEVEL
     *
     * @mbg.generated
     */
    private Short level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan.TRAINING_DAY
     *
     * @mbg.generated
     */
    private Short trainingDay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan.COST
     *
     * @mbg.generated
     */
    private String cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan.VOCATION
     *
     * @mbg.generated
     */
    private Boolean vocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan.DEFAULT_STATUS
     *
     * @mbg.generated
     */
    private Short defaultStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan.PLAN_ID
     *
     * @return the value of tm_plan.PLAN_ID
     *
     * @mbg.generated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan.PLAN_ID
     *
     * @param planId the value for tm_plan.PLAN_ID
     *
     * @mbg.generated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan.LEVEL
     *
     * @return the value of tm_plan.LEVEL
     *
     * @mbg.generated
     */
    public Short getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan.LEVEL
     *
     * @param level the value for tm_plan.LEVEL
     *
     * @mbg.generated
     */
    public void setLevel(Short level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan.TRAINING_DAY
     *
     * @return the value of tm_plan.TRAINING_DAY
     *
     * @mbg.generated
     */
    public Short getTrainingDay() {
        return trainingDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan.TRAINING_DAY
     *
     * @param trainingDay the value for tm_plan.TRAINING_DAY
     *
     * @mbg.generated
     */
    public void setTrainingDay(Short trainingDay) {
        this.trainingDay = trainingDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan.COST
     *
     * @return the value of tm_plan.COST
     *
     * @mbg.generated
     */
    public String getCost() {
        return cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan.COST
     *
     * @param cost the value for tm_plan.COST
     *
     * @mbg.generated
     */
    public void setCost(String cost) {
        this.cost = cost == null ? null : cost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan.VOCATION
     *
     * @return the value of tm_plan.VOCATION
     *
     * @mbg.generated
     */
    public Boolean getVocation() {
        return vocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan.VOCATION
     *
     * @param vocation the value for tm_plan.VOCATION
     *
     * @mbg.generated
     */
    public void setVocation(Boolean vocation) {
        this.vocation = vocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan.DEFAULT_STATUS
     *
     * @return the value of tm_plan.DEFAULT_STATUS
     *
     * @mbg.generated
     */
    public Short getDefaultStatus() {
        return defaultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan.DEFAULT_STATUS
     *
     * @param defaultStatus the value for tm_plan.DEFAULT_STATUS
     *
     * @mbg.generated
     */
    public void setDefaultStatus(Short defaultStatus) {
        this.defaultStatus = defaultStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan.CREATE_BY
     *
     * @return the value of tm_plan.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan.CREATE_BY
     *
     * @param createBy the value for tm_plan.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan.CREATE_ON
     *
     * @return the value of tm_plan.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan.CREATE_ON
     *
     * @param createOn the value for tm_plan.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }
}