package com.troytan.sixpack.domain;

import java.util.Date;

public class PlanDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan_detail.PLAN_DETAIL_ID
     *
     * @mbg.generated
     */
    private Integer planDetailId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan_detail.PLAN_ID
     *
     * @mbg.generated
     */
    private Integer planId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan_detail.VIDEO_ID
     *
     * @mbg.generated
     */
    private Integer videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan_detail.REPETITIONS
     *
     * @mbg.generated
     */
    private Short repetitions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan_detail.SETS
     *
     * @mbg.generated
     */
    private Short sets;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan_detail.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_plan_detail.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan_detail.PLAN_DETAIL_ID
     *
     * @return the value of tm_plan_detail.PLAN_DETAIL_ID
     *
     * @mbg.generated
     */
    public Integer getPlanDetailId() {
        return planDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan_detail.PLAN_DETAIL_ID
     *
     * @param planDetailId the value for tm_plan_detail.PLAN_DETAIL_ID
     *
     * @mbg.generated
     */
    public void setPlanDetailId(Integer planDetailId) {
        this.planDetailId = planDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan_detail.PLAN_ID
     *
     * @return the value of tm_plan_detail.PLAN_ID
     *
     * @mbg.generated
     */
    public Integer getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan_detail.PLAN_ID
     *
     * @param planId the value for tm_plan_detail.PLAN_ID
     *
     * @mbg.generated
     */
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan_detail.VIDEO_ID
     *
     * @return the value of tm_plan_detail.VIDEO_ID
     *
     * @mbg.generated
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan_detail.VIDEO_ID
     *
     * @param videoId the value for tm_plan_detail.VIDEO_ID
     *
     * @mbg.generated
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan_detail.REPETITIONS
     *
     * @return the value of tm_plan_detail.REPETITIONS
     *
     * @mbg.generated
     */
    public Short getRepetitions() {
        return repetitions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan_detail.REPETITIONS
     *
     * @param repetitions the value for tm_plan_detail.REPETITIONS
     *
     * @mbg.generated
     */
    public void setRepetitions(Short repetitions) {
        this.repetitions = repetitions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan_detail.SETS
     *
     * @return the value of tm_plan_detail.SETS
     *
     * @mbg.generated
     */
    public Short getSets() {
        return sets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan_detail.SETS
     *
     * @param sets the value for tm_plan_detail.SETS
     *
     * @mbg.generated
     */
    public void setSets(Short sets) {
        this.sets = sets;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan_detail.CREATE_BY
     *
     * @return the value of tm_plan_detail.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan_detail.CREATE_BY
     *
     * @param createBy the value for tm_plan_detail.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_plan_detail.CREATE_ON
     *
     * @return the value of tm_plan_detail.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_plan_detail.CREATE_ON
     *
     * @param createOn the value for tm_plan_detail.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }
}