package com.troytan.sixpack.domain;

import java.util.Date;

public class VideoDesc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_desc.VIDEO_ID
     *
     * @mbg.generated
     */
    private Integer videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_desc.CHN_NAME
     *
     * @mbg.generated
     */
    private String chnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_desc.ENG_NAME
     *
     * @mbg.generated
     */
    private String engName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_desc.TRAIN_MUSCLE
     *
     * @mbg.generated
     */
    private String trainMuscle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_desc.START_ACTION
     *
     * @mbg.generated
     */
    private String startAction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_desc.ESSEN_EXERCISE
     *
     * @mbg.generated
     */
    private String essenExercise;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_desc.REMIND
     *
     * @mbg.generated
     */
    private String remind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_desc.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_desc.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_desc.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_desc.UPDATE_ON
     *
     * @mbg.generated
     */
    private Date updateOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_desc.VIDEO_ID
     *
     * @return the value of tm_video_desc.VIDEO_ID
     *
     * @mbg.generated
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_desc.VIDEO_ID
     *
     * @param videoId the value for tm_video_desc.VIDEO_ID
     *
     * @mbg.generated
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_desc.CHN_NAME
     *
     * @return the value of tm_video_desc.CHN_NAME
     *
     * @mbg.generated
     */
    public String getChnName() {
        return chnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_desc.CHN_NAME
     *
     * @param chnName the value for tm_video_desc.CHN_NAME
     *
     * @mbg.generated
     */
    public void setChnName(String chnName) {
        this.chnName = chnName == null ? null : chnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_desc.ENG_NAME
     *
     * @return the value of tm_video_desc.ENG_NAME
     *
     * @mbg.generated
     */
    public String getEngName() {
        return engName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_desc.ENG_NAME
     *
     * @param engName the value for tm_video_desc.ENG_NAME
     *
     * @mbg.generated
     */
    public void setEngName(String engName) {
        this.engName = engName == null ? null : engName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_desc.TRAIN_MUSCLE
     *
     * @return the value of tm_video_desc.TRAIN_MUSCLE
     *
     * @mbg.generated
     */
    public String getTrainMuscle() {
        return trainMuscle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_desc.TRAIN_MUSCLE
     *
     * @param trainMuscle the value for tm_video_desc.TRAIN_MUSCLE
     *
     * @mbg.generated
     */
    public void setTrainMuscle(String trainMuscle) {
        this.trainMuscle = trainMuscle == null ? null : trainMuscle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_desc.START_ACTION
     *
     * @return the value of tm_video_desc.START_ACTION
     *
     * @mbg.generated
     */
    public String getStartAction() {
        return startAction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_desc.START_ACTION
     *
     * @param startAction the value for tm_video_desc.START_ACTION
     *
     * @mbg.generated
     */
    public void setStartAction(String startAction) {
        this.startAction = startAction == null ? null : startAction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_desc.ESSEN_EXERCISE
     *
     * @return the value of tm_video_desc.ESSEN_EXERCISE
     *
     * @mbg.generated
     */
    public String getEssenExercise() {
        return essenExercise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_desc.ESSEN_EXERCISE
     *
     * @param essenExercise the value for tm_video_desc.ESSEN_EXERCISE
     *
     * @mbg.generated
     */
    public void setEssenExercise(String essenExercise) {
        this.essenExercise = essenExercise == null ? null : essenExercise.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_desc.REMIND
     *
     * @return the value of tm_video_desc.REMIND
     *
     * @mbg.generated
     */
    public String getRemind() {
        return remind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_desc.REMIND
     *
     * @param remind the value for tm_video_desc.REMIND
     *
     * @mbg.generated
     */
    public void setRemind(String remind) {
        this.remind = remind == null ? null : remind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_desc.CREATE_BY
     *
     * @return the value of tm_video_desc.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_desc.CREATE_BY
     *
     * @param createBy the value for tm_video_desc.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_desc.CREATE_ON
     *
     * @return the value of tm_video_desc.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_desc.CREATE_ON
     *
     * @param createOn the value for tm_video_desc.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_desc.UPDATE_BY
     *
     * @return the value of tm_video_desc.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_desc.UPDATE_BY
     *
     * @param updateBy the value for tm_video_desc.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_desc.UPDATE_ON
     *
     * @return the value of tm_video_desc.UPDATE_ON
     *
     * @mbg.generated
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_desc.UPDATE_ON
     *
     * @param updateOn the value for tm_video_desc.UPDATE_ON
     *
     * @mbg.generated
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }
}