package com.troytan.sixpack.domain;

import java.util.Date;

public class Video {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video.VIDEO_ID
     *
     * @mbg.generated
     */
    private Integer videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video.CATEGORY
     *
     * @mbg.generated
     */
    private Short category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video.DIFFICULTY
     *
     * @mbg.generated
     */
    private Short difficulty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video.duration
     *
     * @mbg.generated
     */
    private Integer duration;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video.ORD
     *
     * @mbg.generated
     */
    private Short ord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video.UPDATE_ON
     *
     * @mbg.generated
     */
    private Date updateOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video.VIDEO_ID
     *
     * @return the value of tm_video.VIDEO_ID
     *
     * @mbg.generated
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video.VIDEO_ID
     *
     * @param videoId the value for tm_video.VIDEO_ID
     *
     * @mbg.generated
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video.CATEGORY
     *
     * @return the value of tm_video.CATEGORY
     *
     * @mbg.generated
     */
    public Short getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video.CATEGORY
     *
     * @param category the value for tm_video.CATEGORY
     *
     * @mbg.generated
     */
    public void setCategory(Short category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video.DIFFICULTY
     *
     * @return the value of tm_video.DIFFICULTY
     *
     * @mbg.generated
     */
    public Short getDifficulty() {
        return difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video.DIFFICULTY
     *
     * @param difficulty the value for tm_video.DIFFICULTY
     *
     * @mbg.generated
     */
    public void setDifficulty(Short difficulty) {
        this.difficulty = difficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video.duration
     *
     * @return the value of tm_video.duration
     *
     * @mbg.generated
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video.duration
     *
     * @param duration the value for tm_video.duration
     *
     * @mbg.generated
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video.ORD
     *
     * @return the value of tm_video.ORD
     *
     * @mbg.generated
     */
    public Short getOrd() {
        return ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video.ORD
     *
     * @param ord the value for tm_video.ORD
     *
     * @mbg.generated
     */
    public void setOrd(Short ord) {
        this.ord = ord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video.CREATE_BY
     *
     * @return the value of tm_video.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video.CREATE_BY
     *
     * @param createBy the value for tm_video.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video.CREATE_ON
     *
     * @return the value of tm_video.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video.CREATE_ON
     *
     * @param createOn the value for tm_video.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video.UPDATE_BY
     *
     * @return the value of tm_video.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video.UPDATE_BY
     *
     * @param updateBy the value for tm_video.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video.UPDATE_ON
     *
     * @return the value of tm_video.UPDATE_ON
     *
     * @mbg.generated
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video.UPDATE_ON
     *
     * @param updateOn the value for tm_video.UPDATE_ON
     *
     * @mbg.generated
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }
}