package com.troytan.sixpack.domain;

import java.util.Date;

public class VideoRc {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_rc.VIDEO_RC_ID
     *
     * @mbg.generated
     */
    private Integer videoRcId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_rc.VIDEO_ID
     *
     * @mbg.generated
     */
    private Integer videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_rc.GENDER
     *
     * @mbg.generated
     */
    private Short gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_rc.VIDEO_URL
     *
     * @mbg.generated
     */
    private String videoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_rc.THUMBNAIL_URL
     *
     * @mbg.generated
     */
    private String thumbnailUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_rc.AUDIO_URL
     *
     * @mbg.generated
     */
    private String audioUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_rc.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_rc.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_rc.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tm_video_rc.UPDATE_ON
     *
     * @mbg.generated
     */
    private Date updateOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_rc.VIDEO_RC_ID
     *
     * @return the value of tm_video_rc.VIDEO_RC_ID
     *
     * @mbg.generated
     */
    public Integer getVideoRcId() {
        return videoRcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_rc.VIDEO_RC_ID
     *
     * @param videoRcId the value for tm_video_rc.VIDEO_RC_ID
     *
     * @mbg.generated
     */
    public void setVideoRcId(Integer videoRcId) {
        this.videoRcId = videoRcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_rc.VIDEO_ID
     *
     * @return the value of tm_video_rc.VIDEO_ID
     *
     * @mbg.generated
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_rc.VIDEO_ID
     *
     * @param videoId the value for tm_video_rc.VIDEO_ID
     *
     * @mbg.generated
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_rc.GENDER
     *
     * @return the value of tm_video_rc.GENDER
     *
     * @mbg.generated
     */
    public Short getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_rc.GENDER
     *
     * @param gender the value for tm_video_rc.GENDER
     *
     * @mbg.generated
     */
    public void setGender(Short gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_rc.VIDEO_URL
     *
     * @return the value of tm_video_rc.VIDEO_URL
     *
     * @mbg.generated
     */
    public String getVideoUrl() {
        return videoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_rc.VIDEO_URL
     *
     * @param videoUrl the value for tm_video_rc.VIDEO_URL
     *
     * @mbg.generated
     */
    public void setVideoUrl(String videoUrl) {
        this.videoUrl = videoUrl == null ? null : videoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_rc.THUMBNAIL_URL
     *
     * @return the value of tm_video_rc.THUMBNAIL_URL
     *
     * @mbg.generated
     */
    public String getThumbnailUrl() {
        return thumbnailUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_rc.THUMBNAIL_URL
     *
     * @param thumbnailUrl the value for tm_video_rc.THUMBNAIL_URL
     *
     * @mbg.generated
     */
    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl == null ? null : thumbnailUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_rc.AUDIO_URL
     *
     * @return the value of tm_video_rc.AUDIO_URL
     *
     * @mbg.generated
     */
    public String getAudioUrl() {
        return audioUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_rc.AUDIO_URL
     *
     * @param audioUrl the value for tm_video_rc.AUDIO_URL
     *
     * @mbg.generated
     */
    public void setAudioUrl(String audioUrl) {
        this.audioUrl = audioUrl == null ? null : audioUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_rc.CREATE_BY
     *
     * @return the value of tm_video_rc.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_rc.CREATE_BY
     *
     * @param createBy the value for tm_video_rc.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_rc.CREATE_ON
     *
     * @return the value of tm_video_rc.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_rc.CREATE_ON
     *
     * @param createOn the value for tm_video_rc.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_rc.UPDATE_BY
     *
     * @return the value of tm_video_rc.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_rc.UPDATE_BY
     *
     * @param updateBy the value for tm_video_rc.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tm_video_rc.UPDATE_ON
     *
     * @return the value of tm_video_rc.UPDATE_ON
     *
     * @mbg.generated
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tm_video_rc.UPDATE_ON
     *
     * @param updateOn the value for tm_video_rc.UPDATE_ON
     *
     * @mbg.generated
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }
}