package com.troytan.sixpack.domain;

import java.util.Date;

public class Vote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote.VOTE_ID
     *
     * @mbg.generated
     */
    private Integer voteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote.VALUE
     *
     * @mbg.generated
     */
    private Short value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote.USER_ID
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote.DEBATE_ID
     *
     * @mbg.generated
     */
    private Integer debateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote.SUBJECT_ID
     *
     * @mbg.generated
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote.VOTE_ID
     *
     * @return the value of tt_vote.VOTE_ID
     *
     * @mbg.generated
     */
    public Integer getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote.VOTE_ID
     *
     * @param voteId the value for tt_vote.VOTE_ID
     *
     * @mbg.generated
     */
    public void setVoteId(Integer voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote.VALUE
     *
     * @return the value of tt_vote.VALUE
     *
     * @mbg.generated
     */
    public Short getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote.VALUE
     *
     * @param value the value for tt_vote.VALUE
     *
     * @mbg.generated
     */
    public void setValue(Short value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote.USER_ID
     *
     * @return the value of tt_vote.USER_ID
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote.USER_ID
     *
     * @param userId the value for tt_vote.USER_ID
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote.DEBATE_ID
     *
     * @return the value of tt_vote.DEBATE_ID
     *
     * @mbg.generated
     */
    public Integer getDebateId() {
        return debateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote.DEBATE_ID
     *
     * @param debateId the value for tt_vote.DEBATE_ID
     *
     * @mbg.generated
     */
    public void setDebateId(Integer debateId) {
        this.debateId = debateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote.SUBJECT_ID
     *
     * @return the value of tt_vote.SUBJECT_ID
     *
     * @mbg.generated
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote.SUBJECT_ID
     *
     * @param subjectId the value for tt_vote.SUBJECT_ID
     *
     * @mbg.generated
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote.CREATE_BY
     *
     * @return the value of tt_vote.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote.CREATE_BY
     *
     * @param createBy the value for tt_vote.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote.CREATE_ON
     *
     * @return the value of tt_vote.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote.CREATE_ON
     *
     * @param createOn the value for tt_vote.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }
}