package com.troytan.sixpack.domain;

import java.util.Date;

public class VoteSubject {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote_subject.SUBJECT_ID
     *
     * @mbg.generated
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote_subject.TITLE
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote_subject.CONTENT
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote_subject.OBVERSE
     *
     * @mbg.generated
     */
    private String obverse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote_subject.REVERSE
     *
     * @mbg.generated
     */
    private String reverse;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote_subject.CREATE_BY
     *
     * @mbg.generated
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote_subject.CREATE_ON
     *
     * @mbg.generated
     */
    private Date createOn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote_subject.UPDATE_BY
     *
     * @mbg.generated
     */
    private Integer updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tt_vote_subject.UPDATE_ON
     *
     * @mbg.generated
     */
    private Date updateOn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote_subject.SUBJECT_ID
     *
     * @return the value of tt_vote_subject.SUBJECT_ID
     *
     * @mbg.generated
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote_subject.SUBJECT_ID
     *
     * @param subjectId the value for tt_vote_subject.SUBJECT_ID
     *
     * @mbg.generated
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote_subject.TITLE
     *
     * @return the value of tt_vote_subject.TITLE
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote_subject.TITLE
     *
     * @param title the value for tt_vote_subject.TITLE
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote_subject.CONTENT
     *
     * @return the value of tt_vote_subject.CONTENT
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote_subject.CONTENT
     *
     * @param content the value for tt_vote_subject.CONTENT
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote_subject.OBVERSE
     *
     * @return the value of tt_vote_subject.OBVERSE
     *
     * @mbg.generated
     */
    public String getObverse() {
        return obverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote_subject.OBVERSE
     *
     * @param obverse the value for tt_vote_subject.OBVERSE
     *
     * @mbg.generated
     */
    public void setObverse(String obverse) {
        this.obverse = obverse == null ? null : obverse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote_subject.REVERSE
     *
     * @return the value of tt_vote_subject.REVERSE
     *
     * @mbg.generated
     */
    public String getReverse() {
        return reverse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote_subject.REVERSE
     *
     * @param reverse the value for tt_vote_subject.REVERSE
     *
     * @mbg.generated
     */
    public void setReverse(String reverse) {
        this.reverse = reverse == null ? null : reverse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote_subject.CREATE_BY
     *
     * @return the value of tt_vote_subject.CREATE_BY
     *
     * @mbg.generated
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote_subject.CREATE_BY
     *
     * @param createBy the value for tt_vote_subject.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote_subject.CREATE_ON
     *
     * @return the value of tt_vote_subject.CREATE_ON
     *
     * @mbg.generated
     */
    public Date getCreateOn() {
        return createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote_subject.CREATE_ON
     *
     * @param createOn the value for tt_vote_subject.CREATE_ON
     *
     * @mbg.generated
     */
    public void setCreateOn(Date createOn) {
        this.createOn = createOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote_subject.UPDATE_BY
     *
     * @return the value of tt_vote_subject.UPDATE_BY
     *
     * @mbg.generated
     */
    public Integer getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote_subject.UPDATE_BY
     *
     * @param updateBy the value for tt_vote_subject.UPDATE_BY
     *
     * @mbg.generated
     */
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tt_vote_subject.UPDATE_ON
     *
     * @return the value of tt_vote_subject.UPDATE_ON
     *
     * @mbg.generated
     */
    public Date getUpdateOn() {
        return updateOn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tt_vote_subject.UPDATE_ON
     *
     * @param updateOn the value for tt_vote_subject.UPDATE_ON
     *
     * @mbg.generated
     */
    public void setUpdateOn(Date updateOn) {
        this.updateOn = updateOn;
    }
}