package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.Debate;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface DebateMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_debate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer debateId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_debate
     *
     * @mbg.generated
     */
    int insert(Debate record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_debate
     *
     * @mbg.generated
     */
    Debate selectByPrimaryKey(Integer debateId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_debate
     *
     * @mbg.generated
     */
    List<Debate> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_debate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Debate record);

    /**
     * 非物理删除辩论
     *
     * @author troytan
     * @date 2018年10月25日
     * @param debateId
     */
    void deleteByStatus(Integer debateId);

    /**
     * 获取辩论详情
     *
     * @author troytan
     * @date 2018年10月25日
     * @param debateId
     * @param userId
     * @return
     */
    Debate getDebateDto(@Param("debateId") Integer debateId, @Param("userId") Integer userId);

    /**
     * 获取发送列表
     *
     * @author troytan
     * @date 2018年10月25日
     * @param currentUser
     * @return
     */
    List<Debate> listByUserId(Integer currentUser);
}
