package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.GroupUser;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GroupUserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_group_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer groupUserId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_group_user
     *
     * @mbg.generated
     */
    int insert(GroupUser record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_group_user
     *
     * @mbg.generated
     */
    GroupUser selectByPrimaryKey(Integer groupUserId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_group_user
     *
     * @mbg.generated
     */
    List<GroupUser> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_group_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GroupUser record);

    GroupUser selectByGroupAndOpenId(@Param("groupId") String groupId, @Param("openId") String openId);
}
