package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.Gvote;
import com.troytan.sixpack.dto.GvoteResultDto;
import com.troytan.sixpack.dto.GvoteResultTitle;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GvoteMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer gvoteId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote
     *
     * @mbg.generated
     */
    int insert(Gvote record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote
     *
     * @mbg.generated
     */
    Gvote selectByPrimaryKey(Integer gvoteId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote
     *
     * @mbg.generated
     */
    List<Gvote> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gvote record);

    /**
     * 投票前查询投票详情
     *
     * @author troytan
     * @date 2018年12月26日
     * @param gvoteId
     * @return
     */
    GvoteResultDto selectVoteDetail(Integer gvoteId);

    /**
     * 根据owner获取voteId
     *
     * @author troytan
     * @date 2018年12月27日
     * @param userId
     * @return
     */
    List<Integer> listIdByOwner(Integer userId);

    /**
     * 根据Id获取结果列表
     *
     * @author troytan
     * @date 2018年12月27日
     * @param ids
     * @return
     */
    List<GvoteResultTitle> listVoteByIds(List<Integer> ids);

    /**
     * 更新状态
     *
     * @author troytan
     * @date 2018年12月27日
     * @param userId
     * @param gvoteId
     * @param status
     */
    void updateStatusByUserAndId(@Param("userId") Integer userId, @Param("gvoteId") Integer gvoteId,
                                 @Param("status") short status);
    
    void updateStatusByEndtime();

}
