package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.GvoteResult;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GvoteResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_result
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("gvoteItemId") Integer gvoteItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_result
     *
     * @mbg.generated
     */
    int insert(GvoteResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_result
     *
     * @mbg.generated
     */
    GvoteResult selectByPrimaryKey(@Param("userId") Integer userId, @Param("gvoteItemId") Integer gvoteItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_result
     *
     * @mbg.generated
     */
    List<GvoteResult> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_result
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GvoteResult record);

    int countUserVote(Integer gvoteId, Integer currentUser);
}