package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.GvoteReceive;
import java.util.List;

public interface GvoteReceiveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_receive
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer receiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_receive
     *
     * @mbg.generated
     */
    int insert(GvoteReceive record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_receive
     *
     * @mbg.generated
     */
    GvoteReceive selectByPrimaryKey(Integer receiveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_receive
     *
     * @mbg.generated
     */
    List<GvoteReceive> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_receive
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GvoteReceive record);

    List<Integer> listIdByReceiver(Integer currentUser);
}