package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.GvoteReceive;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GvoteReceiveMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote_receive
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer receiveId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote_receive
     *
     * @mbg.generated
     */
    int insert(GvoteReceive record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote_receive
     *
     * @mbg.generated
     */
    GvoteReceive selectByPrimaryKey(Integer receiveId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote_receive
     *
     * @mbg.generated
     */
    List<GvoteReceive> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote_receive
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GvoteReceive record);

    /**
     * 根据用户获取gvoteId
     *
     * @author troytan
     * @date 2018年12月27日
     * @param userId
     * @return
     */
    List<Integer> listIdByReceiver(Integer userId);

    void deleteByUserAndId(@Param("userId") Integer userId, @Param("gvoteId") Integer gvoteId);

    int countByUserAndVoteId(@Param("userId") Integer userId, @Param("gvoteId") Integer gvoteId);
}
