package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.Gvote;
import com.troytan.sixpack.dto.GvoteResultDto;
import com.troytan.sixpack.dto.GvoteResultTitle;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface GvoteMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer gvoteId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote
     *
     * @mbg.generated
     */
    int insert(Gvote record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote
     *
     * @mbg.generated
     */
    Gvote selectByPrimaryKey(Integer gvoteId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote
     *
     * @mbg.generated
     */
    List<Gvote> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_gvote
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Gvote record);

    /**
     * 投票前查询投票详情
     *
     * @author troytan
     * @date 2018年12月26日
     * @param gvoteId
     * @return
     */
    GvoteResultDto selectVoteDetail(Integer gvoteId);

    /**
     * 更新finished字段状态
     *
     * @author troytan
     * @date 2018年12月26日
     * @param gvoteId
     */
    void finishVote(Integer gvoteId);

    /**
     * 软删除
     *
     * @author troytan
     * @date 2018年12月26日
     * @param currentUser
     * @param gvoteId
     */
    void deleteByUserAndId(@Param("userId") Integer userId, @Param("gvoteId") Integer gvoteId);

    /**
     * 发送列表
     *
     * @author troytan
     * @date 2018年12月26日
     * @param currentUser
     * @return
     */
    List<GvoteResultTitle> listSendVoteByUser(@Param("userId")Integer userId);

    /**
     * 接收列表
     *
     * @author troytan
     * @date 2018年12月26日
     * @param currentUser
     * @return
     */
    List<GvoteResultTitle> listReceiveVoteByUser(Integer currentUser);
}
