package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.GvoteItem;
import com.troytan.sixpack.dto.GvoteItemResult;

import java.util.List;

public interface GvoteItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer gvoteItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_item
     *
     * @mbg.generated
     */
    int insert(GvoteItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_item
     *
     * @mbg.generated
     */
    GvoteItem selectByPrimaryKey(Integer gvoteItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_item
     *
     * @mbg.generated
     */
    List<GvoteItem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_gvote_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GvoteItem record);

    List<GvoteItemResult> listResultByVoteId(Integer gvoteId);
}