package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.Plan;
import com.troytan.sixpack.dto.PlanDto;

import java.util.List;

public interface PlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_plan
     *
     * @mbg.generated
     */
    int insert(Plan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_plan
     *
     * @mbg.generated
     */
    Plan selectByPrimaryKey(Integer planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_plan
     *
     * @mbg.generated
     */
    List<Plan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Plan record);

    List<PlanDto> listPlanByUser(Integer userId);

    short countByLevel(Short level);
}