package com.troytan.sixpack.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.troytan.sixpack.domain.User;

public interface UserMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tm_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    /**
     * 获取用户偏爱的教练
     *
     * @author troytan
     * @date 2018年10月9日
     * @param userId
     * @return
     */
    Short getPreferByUserId(Integer userId);

    /**
     * 更新用户教练性别
     *
     * @author troytan
     * @date 2018年10月10日
     * @param currentUser
     * @param gender
     */
    void updatePreferByUserId(@Param("userId") Integer currentUser, @Param("prefer") Short gender);

    User selectByOpenId(String openid);

    void updateBySelective(User user);
}
