package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.VideoRc;
import com.troytan.sixpack.dto.VideoDetailDto;

import java.util.List;

public interface VideoRcMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tm_video_rc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer videoRcId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tm_video_rc
     *
     * @mbg.generated
     */
    int insert(VideoRc record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tm_video_rc
     *
     * @mbg.generated
     */
    VideoRc selectByPrimaryKey(Integer videoRcId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tm_video_rc
     *
     * @mbg.generated
     */
    List<VideoRc> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tm_video_rc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VideoRc record);

    /**
     * 获取单个视频详情
     *
     * @author troytan
     * @date 2018年10月9日
     * @param videoRcId
     * @return
     */
    VideoDetailDto getVideoDetail(Integer videoRcId);
}
