package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.VideoDesc;
import java.util.List;

public interface VideoDescMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_video_desc
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_video_desc
     *
     * @mbg.generated
     */
    int insert(VideoDesc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_video_desc
     *
     * @mbg.generated
     */
    VideoDesc selectByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_video_desc
     *
     * @mbg.generated
     */
    List<VideoDesc> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tm_video_desc
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VideoDesc record);
}