package com.troytan.sixpack.repository;

import com.troytan.sixpack.domain.Vote;
import com.troytan.sixpack.domain.VoteSubject;
import com.troytan.sixpack.dto.VoteResult;

import java.util.List;

public interface VoteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_vote
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer voteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_vote
     *
     * @mbg.generated
     */
    int insert(Vote record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_vote
     *
     * @mbg.generated
     */
    Vote selectByPrimaryKey(Integer voteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_vote
     *
     * @mbg.generated
     */
    List<Vote> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tt_vote
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Vote record);

    VoteResult getVoteResult(Integer subjectId);

    List<VoteSubject> listByUserId(Integer currentUser);
}