package com.troytan.sixpack.repository;

import java.util.List;

import com.troytan.sixpack.domain.Vote;
import com.troytan.sixpack.dto.AnonymousVoteResult;
import com.troytan.sixpack.dto.DebateResult;
import com.troytan.sixpack.dto.RealVoteResult;
import com.troytan.sixpack.dto.VoteResult;

public interface VoteMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_vote
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer voteId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_vote
     *
     * @mbg.generated
     */
    int insert(Vote record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_vote
     *
     * @mbg.generated
     */
    Vote selectByPrimaryKey(Integer voteId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_vote
     *
     * @mbg.generated
     */
    List<Vote> selectAll();

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table tt_vote
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Vote record);

    VoteResult getVoteResult(Integer subjectId);

    AnonymousVoteResult getVoteResultWithOutUser(Integer subjectId);

    List<RealVoteResult> getVoteResultWithUser(Integer subjectId);

    DebateResult getDebateResult(Integer debateId);
}
